---
title: "Capstone Machine Learning"
author: "Frank"
date: "October 23, 2017"
output: html_document
---

## Capstone Machine Learning

1. How do you frame your main question as a machine learning problem? Is it a supervised or unsupervised problem? If it is supervised, is it a regression or a classification?
I will be basing my model on the how the loan originated. To do this, I will be using logistic regression model to predict.

2. What are the main features (also called independent variables or 
predictors) that you'll use?
The dependent variable will be as stated previously, "Loans Originated". The independent variables will be: Ethnicity, Race, Co_applicant, sex, county, hoepa status, lien status, loan purpose, loan type, owner occupancy, preapprovals, property types and purchaser type.

3. Which machine learning technique will you use?
How will you evaluate the success of your machine learning technique? What metric will you use? 
The regression model will be the first step process. 
To understand if another model can be more accurate, I will also be using CART model for compare and contrast.
The CART model will be checked for accuracy based on pROC function.
